/* ─────────────────────────────────────────────────────────────────────────────
 * ERZEUGT — nicht von Hand aendern.
 *
 * Quelle:  lib/agents/material/forbidden-words.md, Abschnitte A bis I
 * Erzeugt: python3 scripts/verbote-generieren.py
 *
 * Abschnitt J (Satzzeichen), K (ausdruecklich erlaubt), L und M (strukturelle
 * Verbote) stehen nicht hier — dafuer gibt es eigene Regeln in lint.ts.
 *
 * `kontext: true` heisst: Die Quelle verbietet das Wort nur in einer Lesart
 * ("bildlos", "ausser Klima-Kontext", "als Phrase"). Solche Treffer sind
 * Warnungen, keine Fehler — das Urteil bleibt beim Menschen.
 * ──────────────────────────────────────────────────────────────────────────── */

export interface VerbotenerBegriff { wort: string; gruppe: string; kontext?: boolean }

export const VERBOTENE_BEGRIFFE: VerbotenerBegriff[] = [
  { wort: 'mal ganz ehrlich', gruppe: 'ausdrücklich verboten' },
  { wort: 'Hand aufs Herz', gruppe: 'ausdrücklich verboten' },
  { wort: 'lass uns ehrlich sein', gruppe: 'ausdrücklich verboten' },
  { wort: 'tragend', gruppe: 'ausdrücklich verboten', kontext: true },
  { wort: 'tragende Rolle', gruppe: 'ausdrücklich verboten' },
  { wort: 'tragende Bedeutung', gruppe: 'ausdrücklich verboten' },
  { wort: 'trägt', gruppe: 'ausdrücklich verboten', kontext: true },
  { wort: 'tragen', gruppe: 'ausdrücklich verboten', kontext: true },
  { wort: 'trägt zum Erfolg bei', gruppe: 'ausdrücklich verboten' },
  { wort: 'Bausteine', gruppe: 'ausdrücklich verboten' },
  { wort: 'DNA', gruppe: 'ausdrücklich verboten', kontext: true },
  { wort: 'steckt in unserer DNA', gruppe: 'ausdrücklich verboten' },
  { wort: 'auf Steroide', gruppe: 'ausdrücklich verboten' },
  { wort: 'X on steroids', gruppe: 'ausdrücklich verboten' },
  { wort: 'fahren', gruppe: 'ausdrücklich verboten', kontext: true },
  { wort: 'eine AI-Toolchain fahren', gruppe: 'ausdrücklich verboten' },
  { wort: 'was rausmuss', gruppe: 'ausdrücklich verboten' },
  { wort: 'torture-getestet', gruppe: 'ausdrücklich verboten' },
  { wort: 'ICP', gruppe: 'ausdrücklich verboten' },
  { wort: 'Pain-Point-Matrix', gruppe: 'ausdrücklich verboten' },
  { wort: 'Awareness-Stage', gruppe: 'ausdrücklich verboten' },
  { wort: 'Wer wartet, holt nicht auf', gruppe: 'ausdrücklich verboten' },
  { wort: 'wird ersetzt', gruppe: 'ausdrücklich verboten' },
  { wort: 'kippt zuerst', gruppe: 'ausdrücklich verboten' },
  { wort: 'Dein Wettbewerb startet bei null', gruppe: 'ausdrücklich verboten' },
  { wort: 'nicht mehr verhandelbar', gruppe: 'ausdrücklich verboten' },
  { wort: 'in der heutigen schnelllebigen Welt', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'letztendlich', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'im Grunde', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'auf den Punkt gebracht', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Mehrwert', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'ganzheitlich', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'synergistisch', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'auf Augenhöhe', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'kraftvoll', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'wirkungsvoll', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'nachhaltig', gruppe: 'AI-Schwurbel (DE)', kontext: true },
  { wort: 'wertstiftend', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'wertvoll', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'value', gruppe: 'AI-Schwurbel (DE)', kontext: true },
  { wort: 'Performance', gruppe: 'AI-Schwurbel (DE)', kontext: true },
  { wort: 'skalieren', gruppe: 'AI-Schwurbel (DE)', kontext: true },
  { wort: 'optimieren', gruppe: 'AI-Schwurbel (DE)', kontext: true },
  { wort: 'effizient', gruppe: 'AI-Schwurbel (DE)', kontext: true },
  { wort: 'synchronisieren', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'disruptiv', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'next level', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'game-changer', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'game-changing', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Need to know', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'must have', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'key learning', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Stellschrauben', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Hebel ansetzen', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'aufs nächste Level heben', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'aus der Komfortzone treten', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Wachstumsschmerzen', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Quantensprung', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'unsere DNA', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'unser Why', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Mindset', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'nahtlos', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'State of the Art', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'innovativ und zuverlässig', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Seat', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'Cohort', gruppe: 'AI-Schwurbel (DE)' },
  { wort: 'in today\'s fast-paced world', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'at the end of the day', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'level up', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'move the needle', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'low-hanging fruit', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'boil the ocean', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'synergy', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'holistic', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'unlock potential', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'unleash', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'crush it', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'dominate', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'nail it', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'at scale', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'scalable', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'seamless', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'frictionless', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'delight customers', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'delight your buyers', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'value-add', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'value prop', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'north star', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'mindset shift', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'paradigm shift', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'secret sauce', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'magic bullet', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'silver bullet', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'pull the trigger', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'move fast and break things', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'eat your own dog food', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'circle back', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'take this offline', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'going forward', gruppe: 'AI-Schwurbel (EN)' },
  { wort: 'Hot take:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Unpopular opinion:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Real talk:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Here\'s the thing:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Plot twist:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Spoiler:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'POV:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Story time:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'PSA:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Vulnerability post incoming', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Hard pill to swallow:', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Most people won\'t tell you this', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Nobody talks about this', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'I\'ll say what others won\'t', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Read that again', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Save this post', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Tag someone who needs to see this', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Drop a 🔥 if you agree', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Comment "yes" if', gruppe: 'LinkedIn-Hallmark' },
  { wort: '100% of CEOs say', gruppe: 'LinkedIn-Hallmark' },
  { wort: 'Ich hoffe, diese Mail erreicht Sie gut', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Ich hoffe, Sie hatten ein schönes Wochenende', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Ich melde mich kurz, weil', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Ich wollte mich vorstellen', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Darf ich kurz Ihre Zeit in Anspruch nehmen', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Just checking in', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Following up', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Touching base', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Did you get a chance to look at my last email', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'I know you\'re busy, but', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Could we hop on a quick 15-min call', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Let me know your thoughts', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Looking forward to hearing from you', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'I\'d love to pick your brain', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Quick question for you', gruppe: 'Cold-Mail-Klischee' },
  { wort: 'Du musst', gruppe: 'Übergriffigkeit' },
  { wort: 'Hör auf, X zu tun', gruppe: 'Übergriffigkeit' },
  { wort: 'Du machst es falsch', gruppe: 'Übergriffigkeit' },
  { wort: 'Wenn du das nicht tust, verlierst du', gruppe: 'Übergriffigkeit' },
  { wort: 'Du sabotierst dich selbst', gruppe: 'Übergriffigkeit' },
  { wort: 'Du bist dein eigenes größtes Hindernis', gruppe: 'Übergriffigkeit' },
  { wort: 'Verlass deine Komfortzone', gruppe: 'Übergriffigkeit' },
  { wort: 'Mach dich endlich frei von', gruppe: 'Übergriffigkeit' },
  { wort: 'Du verdienst', gruppe: 'Übergriffigkeit' },
  { wort: 'Reiß dich zusammen', gruppe: 'Übergriffigkeit' },
  { wort: 'ohne versteckten Pitch', gruppe: 'Virtue-Signalling' },
  { wort: 'ohne verdeckte Agenda', gruppe: 'Virtue-Signalling' },
  { wort: 'wir wollen Dich nicht überzeugen', gruppe: 'Virtue-Signalling' },
  { wort: 'Erkenntnisse teilen, nicht überzeugen', gruppe: 'Virtue-Signalling' },
  { wort: 'kein Verkaufsgespräch', gruppe: 'Virtue-Signalling' },
  { wort: 'kostet nichts', gruppe: 'Virtue-Signalling' },
  { wort: 'ganz ohne Verpflichtung', gruppe: 'Virtue-Signalling' },
  { wort: 'unverbindlich und kostenlos', gruppe: 'Virtue-Signalling' },
  { wort: 'wir sind herstellerneutral', gruppe: 'Virtue-Signalling' },
  { wort: 'Ich glaube an Empathie', gruppe: 'Virtue-Signalling' },
  { wort: 'Authentizität ist mir wichtig', gruppe: 'Virtue-Signalling' },
  { wort: 'Mir geht es um echte Verbindung', gruppe: 'Virtue-Signalling' },
  { wort: 'Bei mir steht der Mensch im Mittelpunkt', gruppe: 'Virtue-Signalling' },
  { wort: 'Ich bin ein Mensch, kein Roboter', gruppe: 'Virtue-Signalling' },
  { wort: 'Ich verkaufe nicht, ich helfe', gruppe: 'Virtue-Signalling' },
  { wort: 'Ich habe ein großes Herz für', gruppe: 'Virtue-Signalling' },
  { wort: 'It\'s about people, not numbers', gruppe: 'Virtue-Signalling' },
  { wort: 'Lass mich dir was beibringen', gruppe: 'Besserwissertum' },
  { wort: 'Du kapierst es nur nicht', gruppe: 'Besserwissertum' },
  { wort: 'Ich erkläre das mal für die, die hinten sitzen', gruppe: 'Besserwissertum' },
  { wort: 'Es ist eigentlich ganz einfach', gruppe: 'Besserwissertum' },
  { wort: 'Wie ich bereits gesagt habe', gruppe: 'Besserwissertum' },
  { wort: 'Mansplaining-Pattern', gruppe: 'Besserwissertum' },
  { wort: 'gefühlt', gruppe: 'Verschleierungs-Verb', kontext: true },
  { wort: 'quasi', gruppe: 'Verschleierungs-Verb' },
  { wort: 'irgendwie', gruppe: 'Verschleierungs-Verb' },
  { wort: 'wahrscheinlich', gruppe: 'Verschleierungs-Verb', kontext: true },
  { wort: 'tendenziell', gruppe: 'Verschleierungs-Verb' },
  { wort: 'relativ', gruppe: 'Verschleierungs-Verb', kontext: true },
  { wort: 'in gewisser Weise', gruppe: 'Verschleierungs-Verb' },
  { wort: 'auf eine Art', gruppe: 'Verschleierungs-Verb' },
  { wort: 'nicht unbedingt', gruppe: 'Verschleierungs-Verb' },
]
